apiVersion: apps/v1
kind: Deployment
metadata:
  name:
    nodejs-simple-08-2025-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web-server
  template:
    metadata:
      labels:
        component: web-server
    spec:
      containers:
      - name: web-server
        image: nlapshin/nodejs-simple-08-2025-k8s
        ports:
          - containerPort: 4000
