version: "3.9"

services:
  nginx-reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    hostname: reverse-proxy
    restart: "unless-stopped"

    volumes:
      - ./nginx/config.template:/etc/nginx/conf.d/default.conf

    ports:
      - 8000:80
      - 443:443

    networks:
      - api-network

    depends_on:
      - nodejs-server-1
      - nodejs-server-2


  nodejs-server-1:
    container_name: api-1 # имя контейнеру
    hostname: api_first # hostname контейнера, который будет внутри
    restart: "unless-stopped" # restart policy

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - API_PORT=6000

    networks:
      - api-network

  nodejs-server-2:
    container_name: api-2 # имя контейнеру
    hostname: api_second # hostname контейнера, который будет внутри
    restart: "unless-stopped" # restart policy

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - API_PORT=6000

    networks:
      - api-network
      - cache-network

  nodejs-server-3:
    container_name: api-3 # имя контейнеру
    hostname: api_third # hostname контейнера, который будет внутри
    restart: "unless-stopped" # restart policy

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - API_PORT=6000

    networks:
      - api-network
      - cache-network


  mongo:
    image: mongo:7
    container_name: mongo
    hostname: mongo
    restart: "unless-stopped"

    networks:
      - api-network

  redis-cache:
    image: redis
    container_name: cache
    hostname: cache
    restart: "unless-stopped"

    networks:
      - cache-network

networks:
  api-network:
    driver: bridge

  cache-network:
    driver: bridge
